#!/usr/bin/zsh

python_install(){
	zpackage system install python3 python3-pip python3-venv || return 1

	install_python_venv

	zpackage python install pip

	return 0
}

python_check(){
	[[ ${+PYTHON_BIN} -eq 1 ]] && return $PYTHON_BIN

	PYTHON_BIN=1

	[[ -z $(which python3 2>/dev/null) ]] && return 1
	[[ -z $(which pip3    2>/dev/null) ]] && return 1
	[[ -n $(python3 -v venv 2>1 | grep 'named venv') ]] && return 1

	PYTHON_BIN=0 && return 0
}
